---
- hosts: clientes-nfs
  become: true
  become_method: sudo

  tasks:
  - name: Install nfs utilities
    package:
      name: nfs-utils
      state: present

  - name: Add the NFS share and mount it with fstab
    mount:
      path: /share
      src: 192.168.80.11:/share/folder
      state: mounted
      fstype: nfs
    ignore_errors: True
    register: salida
    async: 30
  - name: Debug salida 
    debug: msg=" {{ salida }}"
    
    
